spring.application.name=fort-of-knowledge-backend
server.port=8081
spring.datasource.url=jdbc:sqlite:../fort-of-knowledge.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=my_super_secure_jwt_key_123_at_least_32_chars_long!
jwt.expiration=86400000

spring.jackson.property-naming-strategy=SNAKE_CASE
